### ISSUE TITLE
Loading DICOM image

### ISSUE THREAD

**Issue by Viet995** [chafey/cornerstoneFileImageLoader#1]
Hi Chris!
I'm building the DICOM website but I have some problems with loading DICOM images. DICOM images have a hundred slice (.dcm extenstion).
I'm  using exampleIamgeLoader for loading DICOM image, so I can use cornerstoneFileImageLoader.
And I also use dicomParser.js for anonymizing DICOM image. And Is it Ok, if I apply it on multiple slice of DICOM image?
Do you have any suggestion!?

**Comment by swederik** [comment]
This repository is deprecated. You can use [Cornerstone WADO Image Loader](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/) to load DICOM files. Yes you will have to load a large number of files, or use more advanced (and larger file size) multi-frame images.

Here is a simple de-identification example with dicomParser: https://rawgit.com/cornerstonejs/dicomParser/master/examples/simpleDeIdentify/index.html if you need to do it in the browser.
